services:
    ppk.phpbb3fixes.listener:
        class: ppk\phpbb3fixes\event\listener
        arguments:
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
